### ISSUE TITLE
Unable to locate a class 

### ISSUE THREAD

**Issue by 1mahdimf** [jtolj/simple-blade-heroicons#4]
when i use this package, laravel show this error 

`Unable to locate a class or view for component [heroicon::o-exclamation].`

**Comment by jtolj** [comment]
Hi @1mahdimf,
I'd be happy to help you troubleshoot this if you could share a little more information.

Could you tell me:
1.) What version of Laravel you are using.
2.) What version of the the package you are using.
3.) An example of your blade template where you are seeing the error.

A few things to check in the meantime:
1.) Be sure the package installed correctly - check for it's presence in composer-lock.json and vendor/jtolj/simple-blade heroicons folder exist.
2.) Clear the Laravel optimize cache: php artisan optimize:clear

**Comment by 1mahdimf** [comment]
Versions
`        "jtolj/simple-blade-heroicons": "^2.0",
        "laravel/framework": "^9.19",`

I use welcome blade template and add this icon
`<x-heroicon::o-exclamation />`

I checked folder is exist and run php artisan optimize:clear but error is exist

**Comment by jtolj** [comment]
@1mahdimf 
Ah, I see. Sorry I missed this at first glance, but `exclamation` is no longer an icon in Heroicons 2.0.

They've made available `exclamation-circle`, `exclamation-triangle`, and `shield-exclamation`.

So you would use, for example: `<x-heroicon::o-exclamation-circle />`.

The full list of available icons is searchable at https://heroicons.com/

Hope that helps!
